### PR TITLE
Adding notebook that I used to make the VectorStoreIndex

### PR DESCRIPTION
**Pull request by edouas**
It is ~250MB in size, so I will share it with you on google drive

### CODE REVIEW

**Comment by jakeflynn56** [comment]
Looks great Ed. Looking forward to using the data.

**Review by MarkUnivWash — APPROVED** [review]
Heat

**Comment by MarkUnivWash** [comment]
I noticed that jake closed this heat PR, that is tragic @jakeflynn56

**Comment by apeled** [comment]
RIP

**Pull request merged**
